<?php

namespace Tempo\Bundle\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityProviderRepository extends EntityRepository
{
}
