<?php

namespace Tempo\Bundle\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tempo\Bundle\ProjectBundle\Entity\Project;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function findByProject(Project $project)
    {
        return array();
    }
}
