tempo_activity_provider_ws:
    pattern: /ws/activity/provider/{providerName}/{projectId}
    defaults:
        _controller: TempoActivityBundle:Activity:provider

activity_test:
    pattern: /activity/test
    defaults:
        _controller: TempoActivityBundle:Activity:test
